// Face preset style configurations — all coords in face-local space (center = 0,0)
// The face renderer applies ctx.translate(cx,cy) then ctx.scale(faceScale,faceScale)
// Coordinate system: face spans roughly ±200 units, eyes at ~y=-65, mouth at ~y=+85

export const FACE_STYLES = {
  GOOGLY:      'googly',
  KAWAII:      'kawaii',
  COMIC:       'comic',
  MINIMALIST:  'minimalist',
  RUBBERHOSE:  'rubberhose',
}

export const STYLE_CONFIGS = {
  googly: {
    id: 'googly',
    name: 'Classic Googly (শসা ও ট্রি স্টাইল)',
    emoji: '🥒',
    description: 'গোল বড় সাদা চোখ, ডায়নামিক মনি ও কার্টুন মুখ।',
    eyeType: 'googly',
    mouthType: 'cartoon',
    // Eye positions (face-local)
    leftEye:  { x: -82, y: -62 },
    rightEye: { x:  82, y: -62 },
    eyeRadius: 60,
    pupilRadius: 22,
    eyeStroke: 5,
    eyeColor: '#ffffff',
    pupilColor: '#111111',
    highlightRadius: 9,
    highlightOffset: { x: 9, y: -9 },
    // Mouth
    mouthCenter: { x: 0, y: 88 },
    mouthWidth: 112,
    mouthColor: '#111111',
    tongueColor: '#e05060',
    teethColor: '#ffffff',
    strokeWidth: 4.5,
    // Extras
    eyebrowEnabled: false,
    cheeksEnabled: false,
    hasBlush: false,
    blushColor: 'rgba(255, 100, 100, 0.3)',
  },

  kawaii: {
    id: 'kawaii',
    name: 'Kawaii / Chibi Cute (কাওয়াই কিউট)',
    emoji: '✨',
    description: 'চকচকে অ্যানিমে চোখ, ডাবল রিফ্লেকশন হাইলাইট ও গোলাপি ব্লাশ গাল।',
    eyeType: 'kawaii',
    mouthType: 'cute',
    leftEye:  { x: -88, y: -58 },
    rightEye: { x:  88, y: -58 },
    eyeRadius: 70,
    eyeWidth:  72,
    eyeHeight: 82,
    pupilRadius: 30,
    irisRadius: 46,
    irisColor: '#4a90d9',
    irisGradientTop: '#7ab8f5',
    irisGradientBot: '#2a5fb0',
    eyeStroke: 3.5,
    eyeColor: '#ffffff',
    pupilColor: '#0a0a1a',
    highlightRadius: 11,
    highlightOffset: { x: 13, y: -16 },
    highlight2Radius: 5,
    highlight2Offset: { x: -9, y: 12 },
    mouthCenter: { x: 0, y: 90 },
    mouthWidth: 62,
    mouthColor: '#cc3366',
    teethColor: '#ffffff',
    strokeWidth: 3,
    eyebrowEnabled: false,
    cheeksEnabled: true,
    hasBlush: true,
    blushColor: 'rgba(255, 140, 170, 0.6)',
    blushRx: 44,
    blushRy: 22,
    blushLeft:  { x: -115, y: -10 },
    blushRight: { x:  115, y: -10 },
  },

  comic: {
    id: 'comic',
    name: 'Retro Comic / Looney (লুনি কমিক)',
    emoji: '💥',
    description: 'ড্রামাটিক ভ্রু, বড় দাঁত, কমিক্যাল এক্সপ্রেশন।',
    eyeType: 'comic',
    mouthType: 'comic',
    leftEye:  { x: -82, y: -66 },
    rightEye: { x:  82, y: -66 },
    eyeWidth:  68,
    eyeHeight: 52,
    eyeRadius: 68,
    pupilRadius: 17,
    eyeStroke: 4.5,
    eyeColor: '#f8fafc',
    pupilColor: '#111111',
    highlightRadius: 6,
    highlightOffset: { x: 7, y: -7 },
    mouthCenter: { x: 0, y: 82 },
    mouthWidth: 130,
    mouthColor: '#111111',
    tongueColor: '#e85060',
    teethColor: '#f8f8f8',
    gumColor: '#ff88aa',
    strokeWidth: 5,
    eyebrowEnabled: true,
    eyebrowLeft:  { x: -82, y: -120 },
    eyebrowRight: { x:  82, y: -120 },
    eyebrowLength: 64,
    eyebrowThickness: 10,
    eyebrowColor: '#111111',
    cheeksEnabled: false,
    hasBlush: false,
    blushColor: 'rgba(239, 68, 68, 0.35)',
  },

  minimalist: {
    id: 'minimalist',
    name: 'Minimalist Dot-Line (মিনিমালিস্ট)',
    emoji: '⬤',
    description: 'ছোট বিন্দু চোখ ও পাতলা মুখ — মডার্ন স্ক্যান্ডিনেভিয়ান স্টাইল।',
    eyeType: 'minimalist',
    mouthType: 'minimalist',
    leftEye:  { x: -70, y: -60 },
    rightEye: { x:  70, y: -60 },
    eyeRadius: 22,
    pupilRadius: 8,
    eyeStroke: 0,
    eyeColor: '#111111',
    pupilColor: '#111111',
    highlightRadius: 4,
    highlightOffset: { x: 4, y: -4 },
    mouthCenter: { x: 0, y: 80 },
    mouthWidth: 80,
    mouthColor: '#111111',
    strokeWidth: 4,
    eyebrowEnabled: false,
    cheeksEnabled: false,
  },

  rubberhose: {
    id: 'rubberhose',
    name: 'Rubber-Hose 1930s (রাবার-হোস)',
    emoji: '🎞',
    description: '১৯৩০-এর দশকের ইঙ্কব্লট অ্যানিমেশন স্টাইল — পাই-কাট সার্কেল চোখ।',
    eyeType: 'rubberhose',
    mouthType: 'rubberhose',
    leftEye:  { x: -78, y: -62 },
    rightEye: { x:  78, y: -62 },
    eyeRadius: 52,
    pieAngle: 55,         // degrees of the pie wedge (pupil/iris window)
    eyeColor: '#111111',
    pupilColor: '#ffffff',
    highlightRadius: 0,
    highlightOffset: { x: 0, y: 0 },
    mouthCenter: { x: 0, y: 85 },
    mouthWidth: 110,
    mouthColor: '#111111',
    strokeWidth: 5.5,
    teethColor: '#ffffff',
    eyebrowEnabled: true,
    eyebrowLeft:  { x: -78, y: -126 },
    eyebrowRight: { x:  78, y: -126 },
    eyebrowLength: 60,
    eyebrowThickness: 9,
    eyebrowColor: '#111111',
    cheeksEnabled: false,
  },
}

export const FACE_PRESETS = Object.values(STYLE_CONFIGS)

export const MOODS = [
  { id: 'normal',    name: 'স্বাভাবিক (Normal)',       icon: '🙂' },
  { id: 'happy',     name: 'খুশি (Happy)',              icon: '😄' },
  { id: 'shocked',   name: 'বিস্মিত (Shocked)',         icon: '😲' },
  { id: 'angry',     name: 'রাগী (Angry)',              icon: '😠' },
  { id: 'sad',       name: 'দুঃখিত (Sad)',              icon: '😢' },
]

export const MOOD_CONFIGS = {
  normal:  { label: 'Normal',  emoji: '😐', color: '#6b7280' },
  happy:   { label: 'Happy',   emoji: '😄', color: '#22c55e' },
  shocked: { label: 'Shocked', emoji: '😲', color: '#f59e0b' },
  angry:   { label: 'Angry',   emoji: '😠', color: '#ef4444' },
  sad:     { label: 'Sad',     emoji: '😢', color: '#3b82f6' },
}
